CREATE TABLE LOAN(
    ID BIGINT AUTO_INCREMENT,
    CLIENTSEMAIL VARCHAR(255),
    CLIENTSINCOME BIGINT,
    CLIENTSNAME VARCHAR(255),
    CLIENTSSURNAME VARCHAR(255),
    CREDITOK BOOLEAN,
    REQUESTEDLOAN BIGINT
)